# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refApp', '0002_auto_20170718_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
