# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ref',
            old_name='last_name',
            new_name='position',
        ),
        migrations.AddField(
            model_name='ref',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ref',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ref',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
