# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:08
from __future__ import unicode_literals

import apps.Login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, validators=[apps.Login.models.validateLengthGreaterThanTwo])),
                ('last_name', models.CharField(max_length=45, validators=[apps.Login.models.validateLengthGreaterThanTwo])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
    ]
